name: Docker Package Test

on: release

jobs:
	main:
    runs-on: ubuntu-latest
    steps:
    	 - 
          name: Checkout
          uses: actions/checkout@v2
      -
         name: Login to GitHub Container Registry
         uses: docker/login-action@v2
         with:
         	registry: ghcr.io
         	username: ${{ github.repository_owner }}
         	password: ${{ secrets.Container-Registry-PAT }}
      -
       name: Build and Push
       uses: docker/build-push-action@v2
       with:
       	context: .
       	file: ./docker-package-test.dockerfile
       	push: true
       	tags: ghcr.io/anthonymonterrosa/docker-package-test:latest
