name: Docker Package Test

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: 29a84147d4c5f090eab87436937afeca783f66ad
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-package-test.dockerfile
          push: true
          tags: ghcr.io/anthonymonterrosa/docker-package-test:latest
